INSERT INTO contatos (nome, ramal, gti_version) VALUES ('Alícia Clemente Moreira', 9001,1);
INSERT INTO contatos (nome, ramal, gti_version) VALUES ('Cecília Paschoal Gonçalves', 9002,1);
INSERT INTO contatos (nome, ramal, gti_version) VALUES ('Cláudio Salgado Prestes', 9003,1);
INSERT INTO contatos (nome, ramal, gti_version) VALUES ('Diogo Rios Rezende', 9004,1);
INSERT INTO contatos (nome, ramal, gti_version) VALUES ('Elisandra Ribeiro Pereira', 9005,1);
INSERT INTO contatos (nome, ramal, gti_version) VALUES ('Eloá Moura Sato', 9006,1);
INSERT INTO contatos (nome, ramal, gti_version) VALUES ('Estefânia Lópes Cabral', 9007,1);
INSERT INTO contatos (nome, ramal, gti_version) VALUES ('Gilson Damasceno Borges', 9008,1);
INSERT INTO contatos (nome, ramal, gti_version) VALUES ('Iago Reis de Almeida', 9009,1);
INSERT INTO contatos (nome, ramal, gti_version) VALUES ('Isaías Machado Ambrósio', 9010,1);
INSERT INTO contatos (nome, ramal, gti_version) VALUES ('Ivone Siqueira de Oliveira', 9011,1);
INSERT INTO contatos (nome, ramal, gti_version) VALUES ('Juliano Fernandes Braga', 9012,1);
INSERT INTO contatos (nome, ramal, gti_version) VALUES ('Lorenzo Caetano Maciel', 9013,1);
INSERT INTO contatos (nome, ramal, gti_version) VALUES ('Maria Nazário Guedes', 9014,1);
INSERT INTO contatos (nome, ramal, gti_version) VALUES ('Miguel Fontana Ximenes', 9015,1);
INSERT INTO contatos (nome, ramal, gti_version) VALUES ('Rita Macedo Martins', 9016,1);
INSERT INTO contatos (nome, ramal, gti_version) VALUES ('Rosa Vale Mantovani', 9017,1);
INSERT INTO contatos (nome, ramal, gti_version) VALUES ('Samuel Rosário Justo', 9018,1);
INSERT INTO contatos (nome, ramal, gti_version) VALUES ('Suzana Carmo Alves', 9019,1);
INSERT INTO contatos (nome, ramal, gti_version) VALUES ('Vítor Delchiaro Furtado', 9020,1);